codecov:
  branch: main  # Only use main branch for badge status
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        if_ci_failed: error
        only_pulls: false
        branches:
          - main
    patch:
      default:
        target: 80%
flags:
  rust:
    paths:
      - astro-math/
    carryforward: true
  python:
    paths:
      - astro-math-py/
    carryforward: true

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  branches:
    - main